django/imelhp/donations/urls.py
from django.contrib import admin
from django.urls import path, include

from donations.views import index, DonationTypeListView, DonationTypeUpdateView, DonationTypeDeleteView, DontationTypeCreateView, DonationProductListView, DonationProductUpdateView, DonationProductDeleteView, DonationProductCreateView, DonationMeasureListView, DonationMeasureUpdateView, DonationMeasureDeleteView, DonationMeasureCreateView, DonationListView, DonationUpdateView, DonationDeleteView, DonationCreateView, DonationDetailView, DonationItemUpdateView, DonationItemCreateView, DonationItemDeleteView, DonationProductGroupListView, DonationProductGroupUpdateView, DonationProductGroupDeleteView, DonationProductGroupCreateView

urlpatterns = [
    # Doacao
    path('', DonationListView.as_view(), name='doacoes'),
    path('<int:donation_pk>/', DonationDetailView.as_view(), name='donation_detail'),
    path('<int:donation_pk>/editar', DonationUpdateView.as_view(), name='donation_edit'),    
    path('<int:donation_pk>/apagar', DonationDeleteView.as_view(), name='donation_delete'),
    path('nova', DonationCreateView.as_view(), name='donation_create'),
    # Tipo
    path('tipo', DonationTypeListView.as_view(), name='tipo'),
    path('tipo/<int:donationtype_pk>/editar', DonationTypeUpdateView.as_view(), name='donationtype_edit'),
    path('tipo/<int:donationtype_pk>/apagar', DonationTypeDeleteView.as_view(), name='donationtype_delete'),
    path('tipo/novo', DontationTypeCreateView.as_view(), name='donationtype_create'),
    # Grupo Produto
    path('grupoproduto', DonationProductGroupListView.as_view(), name='grupoproduto'),
    path('grupoproduto/<int:donationproductgroup_pk>/editar', DonationProductGroupUpdateView.as_view(), name='donationproductgroup_edit'),
    path('grupoproduto/<int:donationproductgroup_pk>/apagar', DonationProductGroupDeleteView.as_view(), name='donationproductgroup_delete'),
    path('grupoproduto/novo', DonationProductGroupCreateView.as_view(), name='donationproductgroup_create'),
    # Produto
    path('produto', DonationProductListView.as_view(), name='produto'),
    path('produto/<int:donationproduct_pk>/editar', DonationProductUpdateView.as_view(), name='donationproduct_edit'),
    path('produto/<int:donationproduct_pk>/apagar', DonationProductDeleteView.as_view(), name='donationproduct_delete'),
    path('produto/novo', DonationProductCreateView.as_view(), name='donationproduct_create'),
    # Medida
    path('medida', DonationMeasureListView.as_view(), name='medida'),
    path('medida/<int:donationmeasure_pk>/editar', DonationMeasureUpdateView.as_view(), name='donationmeasure_edit'),
    path('medida/<int:donationmeasure_pk>/apagar', DonationMeasureDeleteView.as_view(), name='donationmeasure_delete'),
    path('medida/nova', DonationMeasureCreateView.as_view(), name='donationmeasure_create'),
    # Item de Doacao
    path('<int:donation_pk>/item/<int:donationitem_pk>/', DonationItemUpdateView.as_view(), name='donationitem_edit'),
    path('<int:donation_pk>/item/<int:donationitem_pk>/apagar', DonationItemDeleteView.as_view(), name='donationitem_delete'),
    path('<int:donation_pk>/item/novo', DonationItemCreateView.as_view(), name='donationitem_create'),
]

django/imelhp/imelhp/urls.py
from django.contrib import admin
from django.urls import path, include

# Remover depois
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('doacoes/', include('donations.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/imelhp/donations/models.py
from django.db import models
import json

# Create your models here.

# Group of product: Cloth, food, ...
class DonationProductGroup(models.Model):
    name = models.CharField(max_length = 30)

    def __str__(self):
        return self.name


# The item of donation: Sugar, Money, Oil
class DonationProduct(models.Model):
    name = models.CharField(max_length = 50)
    group = models.ForeignKey(DonationProductGroup, on_delete = models.CASCADE)
    
    def __str__(self):
        return self.name

# Each donation item has one or more measures: Kg, L, ...
class DonationMeasure(models.Model):
    name = models.CharField(max_length = 20)
    item = models.ManyToManyField(DonationProduct)

    def __str__(self):
        return f'{self.name}'

# A Donation could be received (raise the stock) or delivered (lowers the stock)
class DonationType(models.Model):
    name = models.CharField(max_length = 20)
    add_to_stock = models.BooleanField(default = False)

    def __str__(self):
        if self.add_to_stock:
            operation = '(+)'
        else:
            operation = '(-)'
            
        return f'{self.name} {operation}'


# We have a donation with a date, a type and a list of DonationItems
class Donation(models.Model):
    date = models.DateField()
    type = models.ForeignKey(DonationType, on_delete = models.CASCADE)
    comment = models.CharField(max_length=200, default='')
    
    def __str__(self):
        return f'{self.date} - {self.comment} [{self.type}]'

# Finally, each donation is a list of items containing one product, with some measure and a quantity
class DonationItem(models.Model):
    product = models.ForeignKey(DonationProduct, on_delete = models.CASCADE)
    measure = models.ForeignKey(DonationMeasure, on_delete = models.CASCADE)
    quantity = models.FloatField()
    donation = models.ForeignKey(Donation, on_delete = models.CASCADE)
    
    def save(self, *args, **kwargs):
        self.quantity = round(self.quantity, 2)
        super(DonationItem, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.donation} - {self.quantity} {self.measure} de {self.product}'
    
    class Meta:
        unique_together = (("donation", "product", "measure"),)

django/imelhp/donations/forms.py
from django.utils.translation import gettext_lazy as _

from django import forms
from django.core.exceptions import ValidationError

from donations.models import DonationType, DonationProduct, DonationProductGroup, DonationMeasure, Donation, DonationItem


class DonationTypeForm(forms.ModelForm):

    name = forms.CharField(label = 'Tipo de Doação')
    add_to_stock = forms.BooleanField(label = 'Este tipo de doação adiciona itens doados ao estoque', required=False)
    
    class Meta:
        model = DonationType
        fields = ['name', 'add_to_stock']

class DonationProductGroupForm(forms.ModelForm):

    name = forms.CharField(label = 'Produto')
    
    class Meta:
        model = DonationProductGroup
        fields = ['name']

class DonationProductForm(forms.ModelForm):

    name = forms.CharField(label = 'Produto')
    group = forms.ModelChoiceField(label = 'Grupo de Produto', queryset = DonationProductGroup.objects.all())
    
    class Meta:
        model = DonationProduct
        fields = ['name', 'group']

class DonationMeasureForm(forms.ModelForm):

    name = forms.CharField(label = 'Medida')
    item = forms.ModelMultipleChoiceField(queryset=DonationProduct.objects.all().order_by('name'), label = 'Se aplica a')

    class Meta:
        model = DonationMeasure
        fields = ['name', 'item']

class DonationForm(forms.ModelForm):

    date = forms.DateField(label = 'Data')
    type = forms.ModelChoiceField(label = 'Tipo de Doação', queryset = DonationType.objects.all())
    comment = forms.CharField(label = 'Descrição')
    
    class Meta:
        model = Donation
        fields = ['date', 'type', 'comment']

class DonationItemForm(forms.ModelForm):

    product = forms.ModelChoiceField(label = 'Produto', queryset = DonationProduct.objects.all().order_by('name'))
    quantity = forms.FloatField(label = 'Quantidade', min_value=0.1)
    measure = forms.ModelChoiceField(label = 'Medida', queryset = DonationMeasure.objects.all().order_by('name'))
    
    def clean_measure(self):
        form_measure = self.cleaned_data['measure']
        if 'product' in self.cleaned_data:
            form_product = self.cleaned_data['product']
            valid = len(DonationMeasure.objects.filter(name=form_measure).filter(item=form_product)) > 0
            if not valid:
                raise ValidationError("Medida inválida para este produto")
        return form_measure

    class Meta:
        model = DonationItem
        fields = ['product', 'quantity', 'measure']

django/imelhp/donations/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core.exceptions import ValidationError
from django.db.models import Count, F, Q

from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView, DetailView

from donations.models import DonationType, DonationProduct, DonationProductGroup, DonationMeasure, Donation, DonationItem 
from donations.forms import DonationTypeForm, DonationProductForm, DonationProductGroupForm, DonationMeasureForm, DonationForm, DonationItemForm


# Dontation Type

class DonationTypeListView(ListView):
    model = DonationType
    context_object_name = 'DonationTypes'

class DonationTypeUpdateView(UpdateView):
    model = DonationType
    form_class = DonationTypeForm
    template_name = 'form.html'
    pk_url_kwarg = 'donationtype_pk'
    success_url = reverse_lazy('tipo')

class DonationTypeDeleteView(DeleteView):
    model = DonationType
    pk_url_kwarg = 'donationtype_pk'
    success_url = reverse_lazy('tipo')

class DontationTypeCreateView(CreateView):
    model = DonationType
    form_class = DonationTypeForm
    template_name = 'form.html'
    success_url = reverse_lazy('tipo')

# Donation Product Group

class DonationProductGroupListView(ListView):
    model = DonationProductGroup
    context_object_name = 'DonationProductGroups'

class DonationProductGroupUpdateView(UpdateView):
    model = DonationProductGroup
    form_class = DonationProductGroupForm
    template_name = 'form.html'
    pk_url_kwarg = 'donationproductgroup_pk'
    success_url = reverse_lazy('grupoproduto')

class DonationProductGroupDeleteView(DeleteView):
    model = DonationProductGroup
    pk_url_kwarg = 'donationproductgroup_pk'
    success_url = reverse_lazy('grupoproduto')

class DonationProductGroupCreateView(CreateView):
    model = DonationProductGroup
    template_name = 'form.html'
    form_class = DonationProductGroupForm
    success_url = reverse_lazy('grupoproduto')


# Donation Product

class DonationProductListView(ListView):
    model = DonationProduct
    context_object_name = 'DonationProducts'
    queryset = DonationProduct.objects.all().order_by('name')

class DonationProductUpdateView(UpdateView):
    model = DonationProduct
    form_class = DonationProductForm
    template_name = 'form.html'
    pk_url_kwarg = 'donationproduct_pk'
    success_url = reverse_lazy('produto')

class DonationProductDeleteView(DeleteView):
    model = DonationProduct
    pk_url_kwarg = 'donationproduct_pk'
    success_url = reverse_lazy('produto')

class DonationProductCreateView(CreateView):
    model = DonationProduct
    template_name = 'form.html'
    form_class = DonationProductForm
    success_url = reverse_lazy('produto')

# Donation Measure

class DonationMeasureListView(ListView):
    model = DonationMeasure
    queryset = DonationMeasure.objects.all().order_by('name')
    context_object_name = 'DonationMeasures'

class DonationMeasureUpdateView(UpdateView):
    model = DonationMeasure
    form_class = DonationMeasureForm
    template_name = 'form.html'
    pk_url_kwarg = 'donationmeasure_pk'
    success_url = reverse_lazy('medida')

class DonationMeasureDeleteView(DeleteView):
    model = DonationMeasure
    pk_url_kwarg = 'donationmeasure_pk'
    success_url = reverse_lazy('medida')

class DonationMeasureCreateView(CreateView):
    model = DonationMeasure
    template_name = 'form.html'
    form_class = DonationMeasureForm
    success_url = reverse_lazy('medida')

# Donation

class DonationListView(ListView):
    model = Donation
    context_object_name = 'Donations'
    queryset = Donation.objects.all().order_by('date')

class DonationUpdateView(UpdateView):
    model = Donation
    form_class = DonationForm
    template_name = 'donation_form.html'
    pk_url_kwarg = 'donation_pk'
    
    def get_success_url(self):
        pk = self.kwargs['donation_pk']
        return reverse_lazy('donation_detail', kwargs={'donation_pk': pk})


class DonationDetailView(DetailView):
    model = Donation
    pk_url_kwarg = 'donation_pk'

    def get_context_data(self, **kwargs):
        context = super(DonationDetailView, self).get_context_data(**kwargs)
        context['Donations'] = Donation.objects.all().order_by('date')        
        context['Items'] = DonationItem.objects.filter(donation = self.kwargs['donation_pk']).order_by('product')
        products = DonationProduct.objects.filter(pk__in = context['Items'].values('product'))
        # context['Groups'] = DonationProductGroup.objects.filter(pk__in = products.values('group')).order_by('name')
        print(DonationProductGroup.objects.filter(pk__in = products.values('group')).order_by('name'))
        context['Groups'] = DonationItem.objects.values('product__group__name').annotate(group_quantity=Count('product__group__name')).annotate(group=F('product__group__name')).values('group', 'group_quantity')
        print(context['Groups'])
        return context

class DonationDeleteView(DeleteView):
    model = Donation
    pk_url_kwarg = 'donation_pk'
    success_url = reverse_lazy('doacoes')
    
    def get_context_data(self, **kwargs):
        context = super(DonationDeleteView, self).get_context_data(**kwargs)
        context['Items'] = DonationItem.objects.filter(donation = self.kwargs['donation_pk'])
        return context

class DonationCreateView(CreateView):
    model = Donation
    template_name = 'donation_form.html'
    form_class = DonationForm
    success_url = reverse_lazy('doacoes')

# Donation Item

class DonationItemUpdateView(UpdateView):
    model = DonationItem
    template_name = 'form.html'
    pk_url_kwarg = 'donationitem_pk'
    form_class = DonationItemForm
    
    def get_success_url(self):
        pk = self.kwargs['donation_pk']
        return reverse_lazy('donation_detail', kwargs={'donation_pk': pk})

class DonationItemCreateView(CreateView):
    model = DonationItem
    template_name = 'form.html'    
    form_class = DonationItemForm

    def get_success_url(self):
        pk = self.kwargs['donation_pk']
        return reverse_lazy('donation_detail', kwargs={'donation_pk': pk})

    def form_valid(self, form):
        form.instance.donation = Donation.objects.get(pk = self.kwargs['donation_pk'])
        
        # Validando se este item jah existe para esta doacao e medida
        form_donation = form.instance.donation
        form_measure = form.instance.measure
        form_product = form.instance.product
        
        valid = len(DonationItem.objects.filter(donation = form_donation).filter(product = form_product).filter(measure = form_measure)) == 0
        if not valid:
            form.add_error(None, ValidationError(f"{form_product} em {form_measure} já foi doado"))
            return self.form_invalid(form)            
        else:
            return super(DonationItemCreateView, self).form_valid(form)

class DonationItemDeleteView(DeleteView):
    model = DonationItem
    pk_url_kwarg = 'donationitem_pk'

    def get_success_url(self):
        pk = self.kwargs['donation_pk']
        return reverse_lazy('donation_detail', kwargs={'donation_pk': pk})


def index(request):
    return render(request, 'home.html')

django/imelhp/donations/templates/donations/donation_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="row">
	<ul class="collapsible">
        <li class="active">
            <div class="collapsible-header">
                Apagar a doação {{donation.type.name | lower}} "{{donation.comment}}"?
            </div>
            <div class="collapsible-body">
                {% if Items %}
                <table class="striped">
                    <thead>
                        <th class="center">Quantidade</th>
                        <th class="center">Medida</th>
                        <th class="center">Produto</th>
                    </thead>
                    <tbody>
                    {% for item in Items %}
                        <tr>
                            <td class="right">{{ item.quantity }}</td>
                            <td class="center">{{ item.measure }}</td>
                            <td class="center">{{ item.product }}</td>
                        </tr>                            
                    {% endfor %}
                </table>
                {% else %}
                    <p>Sem items cadastrados</p>
                {% endif %}
            </div>
        </li>
	<form method="post" novalidate>
		{% csrf_token %}
        <div class="row">
            <div class="col s6">
                <button type="submit" class="btn btn-primary btn-block red">Apagar</button>
            </div>
            <div class="col s6">
                <input class="btn btn-outline-secondary blue lighten-1" type="button" value="Cancelar" onclick="window.history.go(-1);"/>
            </div>
        </div>
	</form>
</div>
{% endblock %}

django/imelhp/donations/templates/donations/donation_detail.html
{% extends 'donation_list.html' %}

{% load debug_tags %}

{% block doacao %}
    <div class="Section">
        <div class="row valign-wrapper">
            <div class="col s10">
                <h5><b>{{ donation.comment }}</b></h5>
            </div>
            <div class="col s2">
                <a href="{% url 'donation_edit' donation.pk %}"><i class="material-icons small black-text">edit</i></a>
                <a href="{% url 'donation_delete' donation.pk %}"><i class="material-icons small red-text text-accent-4">delete</i></a>
            </div>
        </div>
    </div>
    <div class="divider"></div>
    <div class="Section">
        <ul class="collapsible">
            {% for group in Groups %}
            <li>
                <div class="collapsible-header">
                    <div class="col s10">
                        {{ group.group }}
                    </div>
                    <div class="col s2">
                        {{ group.group_quantity }} itens
                    </div>
                </div>
                <div class="collapsible-body">
                    <table class="striped">
                        <thead>
                            <th class="center">Quantidade</th>
                            <th class="center">Medida</th>
                            <th class="center">Produto</th>
                            <th></th>
                            <th></th>
                        </thead>
                        <tbody>
                        {% for item in Items %}
                            {% if item.product.group.name == group.group %}
                            <tr>
                                <td class="right"><h6>{{item.quantity|floatformat:2}}</h6></td>
                                <td class="center"><h6>{{item.measure}}</h6></td>
                                <td class="center"><h6>{{item.product}}</h6></td>
                                <td><a href="{% url 'donationitem_edit' donation.pk item.pk %}"><i class="material-icons black-text">edit</i></a></td></td>
                                <td><a href="{% url 'donationitem_delete' donation.pk item.pk %}"><i class="material-icons red-text text-accent-4">delete</i></a></td></td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </li>
            {% endfor %}
        </ul>
        <div class="row">
            <div class="right">
                <a class="btn-floating waves-effect waves-light blue tooltipped btn-small" data-position="right" data-tooltip="Novo Item Doado" href="{% url 'donationitem_create' donation.pk %}"><i class="material-icons">add</i></a>
            </div>
        </div>
    </div>
        

{% endblock %}

django/imelhp/donations/templates/donations/donation_list.html
{% extends 'home.html' %}

{% load humanize %}

{% block title %}
Doações
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col s2 left">
            <table class="striped">
                <thead>
                    <th>Data</th>
                    <th>Tipo</th>
                </thead>
                <tbody>            
                {% for donation in Donations %}
                    <tr>
                        <td><a href="{% url 'donation_detail' donation.pk %}">{{ donation.date | date:"d/M/Y" }}</a></td>
                        {% if donation.type.add_to_stock %}
                        <td><i class="material-icons green-text text-accent-4">add_shopping_cart</i></td>
                        {% else %}
                        <td><i class="material-icons red-text text-accent-4">remove_shopping_cart</i></td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="row">
                <div class="right">
                    <a class="btn-floating waves-effect waves-light blue tooltipped" data-position="right" data-tooltip="Nova Doação" href="{% url 'donation_create' %}"><i class="material-icons">add</i></a>
                </div>
            </div>
        </div>
        <div class="col s1"></div>
        <div class="col s8">
            {% block doacao %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

django/imelhp/donations/templates/donations/donationitem_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="row">
        <div class="col s12">
            Remover {{ donationitem.quantity }} {{ donationitem.measure }} de {{ donationitem.product }} da doação {{ donationitem.donation.type.name | lower }} "{{ donationitem.donation.comment }}"?
        </div>
    </div>
	<form method="post" novalidate>
		{% csrf_token %}
        <div class="row">
            <div class="col s6">
                <button type="submit" class="btn btn-primary btn-block red">Apagar</button>
            </div>
            <div class="col s6">
                <input class="btn btn-outline-secondary blue lighten-1" type="button" value="Cancelar" onclick="window.history.go(-1);"/>
            </div>
        </div>
	</form>
</div>
{% endblock %}

django/imelhp/donations/templates/donations/donationmeasure_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<div class="row justify-content-center">
	<p class="card-title">Apagar Medida <i>"{{donationmeasure.name}}"</i>?</p>    
	<form method="post" novalidate>
		{% csrf_token %}
        <div class="row">
            <div class="col s6">
                <button type="submit" class="btn btn-primary btn-block red">Apagar</button>
            </div>
            <div class="col s6">
                <input class="btn btn-outline-secondary blue lighten-1" type="button" value="Cancelar" onclick="window.history.go(-1);"/>
            </div>
        </div>
	</form>
</div>
{% endblock %}

django/imelhp/donations/templates/donations/donationmeasure_list.html
{% extends 'home.html' %}

{% block title %}
Medidas
{% endblock %}

{% block content %}
    <div class="container">
        <table class="striped">
            <thead>
                <th>Nome</th>
                <th>Apagar</th>
            </thead>
            <tbody>            
            {% for measure in DonationMeasures %}
                <tr>
                    <td><a href="{% url 'donationmeasure_edit' measure.pk %}">{{ measure.name }}</a></td>
                    <td><a href="{% url 'donationmeasure_delete' measure.pk %}"><i class="material-icons red-text text-accent-4">delete</i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="right">
                <a class="btn-floating waves-effect waves-light blue tooltipped" data-position="right" data-tooltip="Nova Medida" href="{% url 'donationmeasure_create' %}"><i class="material-icons">add</i></a>
            </div>
        </div>
    </div>
{% endblock %}

django/imelhp/donations/templates/donations/donationproduct_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<div class="row justify-content-center">
	<p class="card-title">Apagar Produto <i>"{{donationproduct.name}}"</i>?</p>    
	<form method="post" novalidate>
		{% csrf_token %}
        <div class="row">
            <div class="col s6">
                <button type="submit" class="btn btn-primary btn-block red">Apagar</button>
            </div>
            <div class="col s6">
                <input class="btn btn-outline-secondary blue lighten-1" type="button" value="Cancelar" onclick="window.history.go(-1);"/>
            </div>
        </div>
	</form>
</div>
{% endblock %}

django/imelhp/donations/templates/donations/donationproduct_list.html
{% extends 'home.html' %}

{% block title %}
Produtos
{% endblock %}

{% block content %}
    <div class="container">
        <table class="striped">
            <thead>
                <th>Nome</th>
                <th>Grupo</th>
                <th>Apagar</th>
            </thead>
            <tbody>            
            {% for product in DonationProducts %}
                <tr>
                    <td><a href="{% url 'donationproduct_edit' product.pk %}">{{ product.name }}</a></td>
                    <td>{{ product.group }}</a></td>
                    <td><a href="{% url 'donationproduct_delete' product.pk %}"><i class="material-icons red-text text-accent-4">delete</i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="right">
                <a class="btn-floating waves-effect waves-light blue tooltipped" data-position="right" data-tooltip="Novo Produto" href="{% url 'donationproduct_create' %}"><i class="material-icons">add</i></a>
            </div>
        </div>
    </div>
{% endblock %}

django/imelhp/donations/templates/donations/donationproductgroup_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<div class="row justify-content-center">
	<p class="card-title">Apagar Grupo de Produtos <i>"{{donationproductgroup.name}}"</i>?</p>    
	<form method="post" novalidate>
		{% csrf_token %}
        <div class="row">
            <div class="col s6">
                <button type="submit" class="btn btn-primary btn-block red">Apagar</button>
            </div>
            <div class="col s6">
                <input class="btn btn-outline-secondary blue lighten-1" type="button" value="Cancelar" onclick="window.history.go(-1);"/>
            </div>
        </div>
	</form>
</div>
{% endblock %}

django/imelhp/donations/templates/donations/donationproductgroup_list.html
{% extends 'home.html' %}

{% block title %}
Grupos de Produto
{% endblock %}


{% block content %}
    <div class="container">
        <table class="striped">
            <thead>
                <th>Nome</th>
                <th>Apagar</th>
            </thead>
            <tbody>            
            {% for productgroup in DonationProductGroups %}
                <tr>
                    <td><a href="{% url 'donationproductgroup_edit' productgroup.pk %}">{{ productgroup.name }}</a></td>
                    <td><a href="{% url 'donationproductgroup_delete' productgroup.pk %}"><i class="material-icons red-text text-accent-4">delete</i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="right">
                <a class="btn-floating waves-effect waves-light blue tooltipped" data-position="right" data-tooltip="Novo Grupo de Produtos" href="{% url 'donationproductgroup_create' %}"><i class="material-icons">add</i></a>
            </div>
        </div>
    </div>
{% endblock %}

django/imelhp/donations/templates/donations/donationtype_confirm_delete.html
{% extends 'home.html' %}

{% block content %}
<div class="row justify-content-center">
	<p class="card-title">Apagar Tipo de Doação <i>"{{donationtype.name}}"</i>?</p>    
	<form method="post" novalidate>
		{% csrf_token %}
        <div class="row">
            <div class="col s6">
                <button type="submit" class="btn btn-primary btn-block red">Apagar</button>
            </div>
            <div class="col s6">
                <input class="btn btn-outline-secondary blue lighten-1" type="button" value="Cancelar" onclick="window.history.go(-1);"/>
            </div>
        </div>
	</form>
</div>
{% endblock %}

django/imelhp/donations/templates/donations/donationtype_list.html
{% extends 'home.html' %}

{% block title %}
Tipos de Doação
{% endblock %}


{% block content %}
    <div class="container">
        <table class="striped">
            <thead>
                <th>Nome</th>
                <th>Estoque</th>
                <th>Apagar</th>
            </thead>
            <tbody>            
            {% for type in DonationTypes %}
                <tr>
                    <td><a href="{% url 'donationtype_edit' type.pk %}">{{ type.name }}</a></td>
                    {% if type.add_to_stock %}
                    <td><i class="material-icons green-text text-accent-4">add_shopping_cart</i></td>
                    {% else %}
                    <td><i class="material-icons red-text text-accent-4">remove_shopping_cart</i></td>
                    {% endif %}
                    <td><a href="{% url 'donationtype_delete' type.pk %}"><i class="material-icons red-text text-accent-4">delete</i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
            <div class="right">
                <a class="btn-floating waves-effect waves-light blue tooltipped" data-position="right" data-tooltip="Novo Tipo de Doação" href="{% url 'donationtype_create' %}"><i class="material-icons">add</i></a>
            </div>
        </div>
    </div>
{% endblock %}